### ISSUE TITLE
Parameter files

### ISSUE THREAD

**Issue by odow** [jump-dev/CPLEX.jl#140]
As part of the rewrite for MOI, I implemented a proper parser of the `cpxconst.h` file to extract out the constants and parameters (see [here](https://github.com/JuliaOpt/CPLEX.jl/pull/139/files#diff-e3b392712fed5746675cb6b3acd49b09R4)).

However, I only have CPLEX 12.6.1 (EDIT and 12.7.0). Does anyone have other versions of the `cpxconst.h` file they could send me so I can rebuild them as well? Alternatively, we could make the build script search for the `cpxconst.h` file and parse it. But that seems a bit more brittle...

cc'ing people who seem to have had different versions @joehuchette @mlubin @Thuener @chriscoey

**Comment by chriscoey** [comment]
I have the latest version. I'll shoot you an email.

**Comment by g001234** [comment]
Just sent v12.80.
