### ISSUE TITLE
implement cbgetnodelp

### ISSUE THREAD

**Issue by bbrunaud** [jump-dev/CPLEX.jl#172]
Hello

I've been trying to use the function `getcallbacknodelp` described in the [CPLEX manual](https://www.ibm.com/support/knowledgecenter/SSSA5P_12.6.0/ilog.odms.cplex.help/refcallablelibrary/mipapi/getcallbacknodelp.html). I managed to generate a `solvecallback` which the manual says that allows more control over the returned pointer. This code gave a segfault. I don't know how to construct the object the function will return the result. 

```julia
function cbgetnodelp(d::CplexCallbackData)
    lpmodel = Model(d.cbdata.model.env)
    stat = @cpx_ccall(getcallbacknodelp, Cint, (Ptr{Void},Ptr{Void},Cint,Ptr{Void}),
                      d.cbdata.model.env.ptr, d.cbdata.cbdata, d.where, lpmodel.lp)
    if stat != 0
        error(CplexError(d.cbdata.model.env, stat).msg)
    end
    return lpmodel
end
```

```
IN SOLVE CALLBACK
Where = 105
Caught exception
julia: ../nptl/pthread_mutex_lock.c:79: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.

signal (6): Aborted
while loading no file, in expression starting on line 0
Segmentation fault (core dumped)
```

Thanks!

**Comment by odow** [comment]
Is this related to https://github.com/JuliaOpt/CPLEX.jl/issues/98

**Comment by bbrunaud** [comment]
@odow Do you see anything wrong in the implementation that might explain the error?.

**Comment by odow** [comment]
Do you have a reproducible example?

By the way,
> error(CplexError(d.cbdata.model.env, stat).msg)

Should just be `throw(CplexError(d.cbdata.model.env, stat))`

**Comment by odow** [comment]
Just to make sure, did you try disabling threads when using the callback?
i.e. `CPX_PARAM_THREADS=1`
https://www.ibm.com/support/knowledgecenter/en/SSSA5P_12.6.3/ilog.odms.cplex.help/CPLEX/Parameters/topics/Threads.html

**Comment by bbrunaud** [comment]
Hi!. Setting the threads to 1 made the segfault go away. However, now I have another problem, I get an error saying that the problem doesn't exist when I try to write it down, for example.

```julia
function mycallback(cb)
    println("IN SOLVE CALLBACK")
    println("Where = $(cb.where)")
    env = cb.cbdata.model.env
    lpmodel = CPLEX.Model(env)
    stat = CPLEX.@cpx_ccall(getcallbacknodelp,Cint,(Ptr{Void},Ptr{Void},Cint,Ptr{Void},),env.ptr,cb.cbdata.cbdata,cb.where,lpmodel.lp)
    println("SUCCESS, stat = $stat")
    CPLEX.@cpx_ccall(writeprob, Cint, (Ptr{Void}, Ptr{Void}, Ptr{Cchar}, Ptr{Cchar},), env.ptr, lpmodel.lp, "firstry.lp", "LP")
end
```

```
IN SOLVE CALLBACK
Where = 105
SUCCESS, stat = 0
CPLEX Error  1009: No problem exists.
```

**Comment by odow** [comment]
To [quote CPLEX](https://www.ibm.com/support/knowledgecenter/SSSA5P_12.6.0/ilog.odms.cplex.help/refcallablelibrary/mipapi/getcallbacknodelp.html)

> Generally, this pointer may be used only in CPLEX Callable Library query routines, such as CPXXsolution/CPXsolution or CPXXgetrows/CPXgetrows

I don't think this is a Julia issue. I would try reaching out to the CPLEX folks for support.

**Comment by bbrunaud** [comment]
I agree. On the other hand, I'm asking for a feature for `CPLEX.jl`. The thing is that when I do this in C code, it works, so CPLEX people will tell that they don't support Julia. The idea is to have an enhancement to support a very powerful callback function.

**Comment by odow** [comment]
If you want the `getcalbacknodelp` feature added to CPLEX.jl, make a PR :)

If you want to be able to write the LP, ask CPLEX to add that to their C API. If it already is (I'm not sure it that is what you are referring to), I'm not sure what the problem is. Have you tried solving the `lpmodel` then writing?
