### ISSUE TITLE
Missing CPLEX statuses: Keyerror 131

### ISSUE THREAD

**Issue by LefterisM** [jump-dev/CPLEX.jl#175]
I believe that file cpx_solve.jl does not support all the current statuses of CPLEX. 

`const status_symbols = Dict(
    1   => :CPX_STAT_OPTIMAL,
    2   => :CPX_STAT_UNBOUNDED,
    3   => :CPX_STAT_INFEASIBLE,
    4   => :CPX_STAT_INForUNBD,
    5   => :CPX_STAT_OPTIMAL_INFEAS,
    6   => :CPX_STAT_NUM_BEST,
    7   => :CPX_STAT_FEASIBLE_RELAXED,
    8   => :CPX_STAT_OPTIMAL_RELAXED,
    10  => :CPX_STAT_ABORT_IT_LIM,
    11  => :CPX_STAT_ABORT_TIME_LIM,
    12  => :CPX_STAT_ABORT_OBJ_LIM,
    13  => :CPX_STAT_ABORT_USER,
    20  => :CPX_STAT_OPTIMAL_FACE_UNBOUNDED,
    21  => :CPX_STAT_ABORT_PRIM_OBJ_LIM,
    22  => :CPX_STAT_ABORT_DUAL_OBJ_LIM,
    101 => :CPXMIP_OPTIMAL,
    102 => :CPXMIP_OPTIMAL_TOL,
    103 => :CPXMIP_INFEASIBLE,
    104 => :CPXMIP_SOL_LIM,
    105 => :CPXMIP_NODE_LIM_FEAS,
    106 => :CPXMIP_NODE_LIM_INFEAS,
    107 => :CPXMIP_TIME_LIM_FEAS,
    108 => :CPXMIP_TIME_LIM_INFEAS,
    109 => :CPXMIP_FAIL_FEAS,
    110 => :CPXMIP_FAIL_INFEAS,
    111 => :CPXMIP_MEM_LIM_FEAS,
    112 => :CPXMIP_MEM_LIM_INFEAS,
    113 => :CPXMIP_ABORT_FEAS,
    114 => :CPXMIP_ABORT_INFEAS,
    115 => :CPXMIP_OPTIMAL_INFEAS,
    116 => :CPXMIP_FAIL_FEAS_NO_TREE,
    117 => :CPXMIP_FAIL_INFEAS_NO_TREE,
    118 => :CPXMIP_UNBOUNDED,
    119 => :CPXMIP_INForUNBD,
    120 => :CPXMIP_FEASIBLE_RELAXED,
    121 => :CPXMIP_OPTIMAL_RELAXED
)`

The official CPLEX webpage contains more possible status for the solver (https://www.ibm.com/support/knowledgecenter/en/SSSA5P_12.5.0/ilog.odms.cplex.help/CPLEX/OverviewAPIs/topics/Solution_status_codes.html).

Namely, the following codes are missing from the dictionary. Is there a reason for this?  The error occurred to me when I set a deterministic time limit that generated key 131 which could not be found in the dictionary resulting in key not found error.

14 | CPX_STAT_FEASIBLE_RELAXED_SUM
15 | CPX_STAT_OPTIMAL_RELAXED_SUM
16 | CPX_STAT_FEASIBLE_RELAXED_INF
17 | CPX_STAT_OPTIMAL_RELAXED_INF
18 | CPX_STAT_FEASIBLE_RELAXED_QUAD
19 | CPX_STAT_OPTIMAL_RELAXED_QUAD
23 | CPX_STAT_FEASIBLE
24 | CPX_STAT_FIRSTORDER
25 | CPX_STAT_ABORT_DETTIME_LIM
30 | CPX_STAT_CONFLICT_FEASIBLE
31 | CPX_STAT_CONFLICT_MINIMAL
32 | CPX_STAT_CONFLICT_ABORT_CONTRADICTION
33 | CPX_STAT_CONFLICT_ABORT_TIME_LIM
34 | CPX_STAT_CONFLICT_ABORT_IT_LIM
35 | CPX_STAT_CONFLICT_ABORT_NODE_LIM
36 | CPX_STAT_CONFLICT_ABORT_OBJ_LIM
37 | CPX_STAT_CONFLICT_ABORT_MEM_LIM
38 | CPX_STAT_CONFLICT_ABORT_USER
39 | CPX_STAT_CONFLICT_ABORT_DETTIME_LIM
122 | CPXMIP_FEASIBLE_RELAXED_INF
123 | CPXMIP_OPTIMAL_RELAXED_INF
124 | CPXMIP_FEASIBLE_RELAXED_QUAD
125 | CPXMIP_OPTIMAL_RELAXED_QUAD
126 | CPXMIP_ABORT_RELAXED
127 | CPXMIP_FEASIBLE
128 | CPXMIP_POPULATESOL_LIM
129 | CPXMIP_OPTIMAL_POPULATED
130 | CPXMIP_OPTIMAL_POPULATED_TOL
131 | CPXMIP_DETTIME_LIM_FEAS
132 | CPXMIP_DETTIME_LIM_INFEAS

Thanks,
Lefteris

**Comment by odow** [comment]
Probably no reason. PR's accepted to add more statuses :)

You will need to add the status to 
https://github.com/JuliaOpt/CPLEX.jl/blob/81d7dbb9947960f56c81f7b32dcdf612fa99f7ba/src/cpx_solve.jl#L248

As well as modifying this function
https://github.com/JuliaOpt/CPLEX.jl/blob/81d7dbb9947960f56c81f7b32dcdf612fa99f7ba/src/CplexSolverInterface.jl#L195
