### ISSUE TITLE
Add support for 64-bit C API

### ISSUE THREAD

**Issue by chengg04** [jump-dev/CPLEX.jl#199]
Just open this issue a record for some future release.

The current CPLEX wrapper calls 32-bit C API, as shown here: https://github.com/JuliaOpt/CPLEX.jl/blob/b4673f12c61256ce6cf4c9d01eccab2601a2474f/src/cpx_common.jl#L3

To add support for 64-bit API, we need to replace "CPX" with "CPXX" in that line. 

According to this [discussion,](https://www.ibm.com/developerworks/community/forums/html/threadTopic?id=77777777-0000-0000-0000-000014911727&ps=25) CPXX is preferred over CPX  because it supports larger models.

**Comment by odow** [comment]
Closing because no one has asked for this before or since. In the future, it should be trivial to wrap the CPXX methods and interface them to the MOI wrapper if required.
