### ISSUE TITLE
How to run different instances at the same time on Cplex using Julia

### ISSUE THREAD

**Issue by samadouz** [jump-dev/CPLEX.jl#208]
Hello,
I have a model and I am trying to run multiple instances in batch mode. I don't know if this is possible using Julia.
Thank you in advance !

**Comment by odow** [comment]
Do you have an example of doing this via the C API? What does batch mode mean?

**Comment by odow** [comment]
This is not available via JuMP/MOI, but the complete C API is now wrapped which may expose the functionality you need.
