### ISSUE TITLE
remaining MOI TODOs

### ISSUE THREAD

**Issue by odow** [jump-dev/CPLEX.jl#264]
There were four remaining TODO's when https://github.com/JuliaOpt/CPLEX.jl/pull/261 was merged:

- [ ] basis status
https://github.com/JuliaOpt/CPLEX.jl/blob/7c4acf18e78e360bb4691fe97b47d2e98d6d29c8/src/MOI/MOI_wrapper.jl#L2491-L2538

- [ ] delete SOC variables
https://github.com/JuliaOpt/CPLEX.jl/blob/7c4acf18e78e360bb4691fe97b47d2e98d6d29c8/test/MathOptInterface/MOI_wrapper.jl#L48-L50

- [x] duals for quadratic problems
https://github.com/JuliaOpt/CPLEX.jl/blob/7c4acf18e78e360bb4691fe97b47d2e98d6d29c8/src/MOI/MOI_wrapper.jl#L2081-L2089

- [x] duals for SOC constraints

**Comment by metab0t** [comment]
@odow I add a prototype of implementing duals for quadratic constraints in #295.
Would you love to take your time to review it and give some advice for further improvement?

**Comment by odow** [comment]
Closing in favor of #323 and #324
