### ISSUE TITLE
Assertion error on optimize!

### ISSUE THREAD

**Issue by mewilhel** [jump-dev/CPLEX.jl#301]
In the MOI.wrapper, in `optimize!` line 1915, the dual status is retrieved by

```
status = MOI.get(model, MOI.DualStatus())
```

this calls
```
function MOI.get(model::Optimizer, attr::MOI.DualStatus)
    _throw_if_optimize_in_progress(model, attr)
    if attr.N != 1
        return MOI.NO_SOLUTION
    elseif model.inner.has_int
        return MOI.NO_SOLUTION
    end
    _, _, primal_stat, dual_stat = c_api_solninfo(model.inner)
    if primal_stat == dual_stat == 1
        return MOI.FEASIBLE_POINT
    elseif primal_stat == 0 && dual_stat == 1
        println("CPLEX TERMINATION STATUS = $(MOI.get(model, MOI.TerminationStatus()))")
        @assert MOI.get(model, MOI.TerminationStatus()) == MOI.INFEASIBLE
        return MOI.INFEASIBILITY_CERTIFICATE
    end
    return MOI.NO_SOLUTION
end
```

Apparently, there is a primal_stat == 0, dual_stat == 1 case that can occur when ` MOI.get(model, MOI.TerminationStatus())` returns a `OTHER_ERROR`.  So, optimize! throws an assertion error rather than terminating. Can we modify this to check for this termination status and return either `MOI.UNKNOWN_RESULT_STATUS` or another status code instead?

**Comment by odow** [comment]
Yes, I don't know why this is like that (even though I think I wrote it). Please make a PR.

**Comment by mewilhel** [comment]
Apparently, the error corresponded to stat code 22 (`CPX_STAT_ABORT_DUAL_OBJ_LIM`). 

Also, I've isolated where this and the behavior here in my use case is rather odd. 

This occurred in an optimization-based bound tightening subroutine where I'm initially solving a problem to feasibility and using active variable constraints to exclude further search directions. Using CPLEX with a `MOI.FEASIBLE_SENSE`, I get this stat code 22 return. If I swap to a Min or Max Sense (or use GLPK) the problem disappears (that is an infeasible result is returned which is correct).

The basic problem is box-constrained plus some `ScalarAffineFunction` in `LessThan` constraints (and the box constraints are well-posed).
