### ISSUE TITLE
Imprecise error message

### ISSUE THREAD

**Issue by viniciusmotta4** [jump-dev/CPLEX.jl#306]
I have a question that I'm not entirely sure if there is an issue with CPLEX.jl. When I try to solve my optimization model, I always receive a "OTHER_ERROR" status message and when I try to access the raw_termination_status, it outputs "Unknown status value". This happens even if I reach a 0.00% gap integer solution. I also know that the problem that I'm trying to solve is feasible and it's possible to find an optimal solution, since I solved it with MOSEK. Is there anyway to find out the real issue with the solution?(a more informative status solution, for example)

I'm using JuMP 0.21.3, CPLEX.jl 0.6.5 and CPLEX 12.10.

**Comment by odow** [comment]
Do you have a small example demonstrating the problem? What is the output of the CPLEX log?

Try the latest master via `] add CPLEX#master`. @mewilhel pushed some fixes to the status reporting.

**Comment by viniciusmotta4** [comment]
Tried with the latest master, and still:


```
Version identifier: 12.10.0.0 | 2019-11-26 | 843d4de2ae
CPXPARAM_MIP_Display                             3
Warning:  Non-integral bounds for integer variables rounded.
Processing 1 MIP starts.
MIP start 'm1' defined solution with objective -1066925.0806.
1 of 1 MIP starts provided solutions.
MIP start 'm1' defined initial solution with objective -1066925.0806.
Warning:  Non-integral bounds for integer variables rounded.
Tried aggregator 13 times.
MIP Presolve eliminated 211669 rows and 88679 columns.
Aggregator did 20110 substitutions.
Reduced MIP has 48378 rows, 16068 columns, and 155568 nonzeros.
Reduced MIP has 6300 binaries, 0 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.80 sec. (705.64 ticks)
Probing fixed 0 vars, tightened 2112 bounds.
Probing time = 0.03 sec. (3.81 ticks)
Tried aggregator 2 times.
Detecting symmetries...
MIP Presolve eliminated 240 rows and 240 columns.
Aggregator did 24 substitutions.
Reduced MIP has 48114 rows, 15804 columns, and 154344 nonzeros.
Reduced MIP has 6300 binaries, 0 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.16 sec. (146.31 ticks)
Probing fixed 0 vars, tightened 360 bounds.
Probing time = 0.09 sec. (3.03 ticks)
MIP emphasis: balance optimality and feasibility.
MIP search method: dynamic search.
Parallel mode: deterministic, using up to 12 threads.
Root relaxation solution time = 2.09 sec. (1064.24 ticks)

        Nodes                                         Cuts/
   Node  Left     Objective  IInf  Best Integer    Best Bound    ItCnt     Gap

*     0+    0                     -1066925.0806        0.0000           100.00%
Found incumbent of value -1066925.080555 after 7.47 sec. (4885.19 ticks)
      0     0 -1066908.0655    24 -1066925.0806 -1066908.0655       63    0.00%

Root node processing (before b&c):
  Real time             =    7.52 sec. (4902.98 ticks)
Parallel b&c, 12 threads:
  Real time             =    0.00 sec. (0.00 ticks)
  Sync time (average)   =    0.00 sec.
  Wait time (average)   =    0.00 sec.
                          ------------
Total (root+branch&cut) =    7.52 sec. (4902.98 ticks)

```
When printing status and raw status:
```
OTHER_ERROR
Unknown status value
```

Small example as a simple model? I can send it, if it's the case

**Comment by viniciusmotta4** [comment]
As I was creating a small example for you this morning, I've discovered why the status of the problem is returning me "OTHER_ERROR" and why I can't retrieve the problem's solution. 

Shortly after I solve this optimization problem, I delete one of the constraints, since I will re-execute this problem with this constraint slightly modified. When I remove this constraint, I can't retrieve the optimal solution and the solution status becomes "OTHER_ERROR". If I retrieve the optimal solution before removing the constraint, it works and the solution status is "OPTIMAL".

If you want to take a look at that, I can send my small example for you to take a look at that. But it seems more like a JuMP issue, which I didn't have when using JuMP 0.20.0 .

PS: Not sure if I should close this issue or not.

**Comment by odow** [comment]
From: https://jump.dev/JuMP.jl/v0.21.1/solutions/#Obtaining-solutions-1

<img width="798" alt="image" src="https://user-images.githubusercontent.com/8177701/86032758-74765d00-b9fd-11ea-8942-17e9a96882e5.png">

**Comment by viniciusmotta4** [comment]
Ok, that explains a lot. Thanks for the help. I'm closing this issue.
