### ISSUE TITLE
set_optimizer_attribute not working in Julia

### ISSUE THREAD

**Issue by JulieAmanda** [jump-dev/CPLEX.jl#307]
Hi, 

I'm using CPLEX with Julia for optimization. I'm trying to change the CPLEX parameters for it to optimize with benders decomposition instead of Branch and Bound with is the default method. I have try to use set_optimizer_attribute/set_optimizer_attributes/ optimizer_with attribute but all in vain.
here are the code I have tried to run : 

solver = CPLEX.Optimizer
md = Model(with_optimizer(solver))
set_optimizer_attribute(md, "CPXPARAM_Benders_Strategy", 0)

but I always get this error "UndefVarError: set_optimizer_attribute not defined" 
 
I already have the packages CPLEX, MOI, JuMP added

Please help! please! what is this not working ? or what can I use otherwise to set the attribute ?

**Comment by odow** [comment]
I've transferred it to CPLEX.jl.

Please ask usage questions like this on the Discourse forum: https://discourse.julialang.org/c/domain/opt/13

The issue is that you are not on the latest version of JuMP (you need `0.21.3`). You can check what is installed with `import Pkg; Pkg.status()`. You can update with `import Pkg; Pkg.update()`.

Here is the syntax you want:
```Julia
model = Model(CPLEX.Optimizer)
set_optimizer_attribute(model, "CPXPARAM_Benders_Strategy", 0)
```

**Comment by JulieAmanda** [comment]
oh sorry I didn't know for the forum. I have note it for next time 
 thank you very much for the answers

I updated my package and got the good JuMP version and it works. so how can I get the strategy CPLEX is using just t verify that the set of attribute was successful ?

**Comment by odow** [comment]
`get_optimizer_attribute(model, "CPXPARAM_Benders_Strategy")`

**Comment by JulieAmanda** [comment]
oh thank you very much for the help !!

**Comment by odow** [comment]
Closing since this seems resolved. Feel free to ask more questions on Discourse in the future :) (We try to keep question on discourse because they are searchable, which means more people read them, and they might be helpful for people in the future.)
