### ISSUE TITLE
unable to locate CPLEX installation 

### ISSUE THREAD

**Issue by mjbushla** [jump-dev/CPLEX.jl#353]
Hello, 

I have tried to run the CPLEX on my MAC but it didn't work, can anyone help me to figure out what is the issue 

┌ Error: Error building `CPLEX`: 
│ ERROR: LoadError: Unable to locate CPLEX installation. Note this must be downloaded separately. See the CPLEX.jl README for further instructions.
│ Stacktrace:
│  [1] error(::String) at /Applications/JuliaPro-1.4.0-1.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
│  [2] try_local_installation() at /Users/moha/.juliapro/JuliaPro_v1.4.0-1/packages/CPLEX/Hxpuk/deps/build.jl:64
│  [3] top-level scope at /Users/moha/.juliapro/JuliaPro_v1.4.0-1/packages/CPLEX/Hxpuk/deps/build.jl:80
│  [4] include(::String) at /Applications/JuliaPro-1.4.0-1.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
│  [5] top-level scope at none:5
│  [6] eval(::Module, ::Any) at /Applications/JuliaPro-1.4.0-1.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
│  [7] exec_options(::Base.JLOptions) at /Applications/JuliaPro-1.4.0-1.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
│  [8] _start() at /Applications/JuliaPro-1.4.0-1.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
│ in expression starting at /Users/moha/.juliapro/JuliaPro_v1.4.0-1/packages/CPLEX/Hxpuk/deps/build.jl:77
└ @ Pkg.Operations /Users/vagrant/worker/juliapro-release-osx1011-0_6/build/tmp_julia/Julia-1.4.app/Contents/Resources/julia/share/julia/stdlib/v1.4/Pkg/src/Operations.jl:892

**Comment by odow** [comment]
You have an old version of Julia installed (JuliaPro 1.4) which is (probably) preventing you from installing the latest version of CPLEX.

Try `import Pkg; Pkg.add(Pkg.PackageSpec(name = "CPLEX", version = v"0.7.6"))`.

If it doesn't because of a conflicting package (docs: https://julialang.github.io/Pkg.jl/v1/managing-packages/#conflicts), remove the conflicting package. 

If it doesn't work because of some "version not found" download and install the latest version (1.5.3) from here: https://julialang.org/downloads/.

It's best not to use JuliaPro because they distribute and older set of packages that may not be compatible with recent solver releases.

**Comment by odow** [comment]
Any update on this? If not, I will close.

**Comment by odow** [comment]
Closing as stale. Please reopen if you still have trouble after following the above instructions.

**Comment by Ratnam-Parikh** [comment]
Hi, I am having an issue while building CPLEX 20.10 and 12.10 on my Macbook M1 air. The error is that it cannot locate the CPLEX installation even though I have given the correct destinations for the binaries. Is the issue due to M1 Arch?

**Comment by odow** [comment]
> Is the issue due to M1 Arch

Did you download a specific version of CPLEX compiled for M1? A generic Mac install will not work. Given 12.10 and 20.1 are quite old, I'm not aware that IBM have released new versions of CPLEX for M1.

This SO answer would seem that they haven't but it's a bit old: https://stackoverflow.com/questions/66859628/cplex-installation-could-not-find-a-version-that-satisfies-and-no-matching

I suggest you contact IBM for support. Note that CPLEX.jl is maintained by the JuMP community and is not an official IBM product.
