### ISSUE TITLE
CPLEX Error  3003: Not a mixed-integer problem.

### ISSUE THREAD

**Issue by henriquebecker91** [jump-dev/CPLEX.jl#355]
I am aware of #173 and #18. The error now happens at CPLEX.jl 0.7.6 (CPLEX 20.1).

The message appears if I call `JuMP.objective_bound` or `JuMP.dual_objective_value` over a a MIP model read from an MPS and relaxed with `JuMP.relax_integrality`. Both CPLEX and Gurobi work as usual (i.e., the expected value is returned) but Gurobi gives no error message (Gurobi.jl 0.9.9, Gurobi 9.1.1).

I annexed a small project/script that should help to reproduce  the problem, given one has the solvers installed and configured: [debug.tar.gz](https://github.com/jump-dev/CPLEX.jl/files/5983557/debug.tar.gz)

While would be interesting to disappear with this message, I am for now only searching for assurance that, other than the extra output, there is no underlying problem here (it cannot give the wrong information, neither am I requesting nonsense).

**Comment by odow** [comment]
I think this is fine to ignore:
https://github.com/jump-dev/CPLEX.jl/blob/d0ab947b63f97338066259dce10a194c9c8d2a5c/src/MOI/MOI_wrapper.jl#L2942-L2951

**Comment by henriquebecker91** [comment]
> I think this is fine to ignore:
> 
> https://github.com/jump-dev/CPLEX.jl/blob/d0ab947b63f97338066259dce10a194c9c8d2a5c/src/MOI/MOI_wrapper.jl#L2942-L2951

hahaha, kinda sloppy technique, but it seems to work and explains the origin of the message.

**Comment by odow** [comment]
Feel free to make a PR improving.
