### ISSUE TITLE
CPLEX 1001: Out of memory and MOI.MEMORY_LIMIT

### ISSUE THREAD

**Issue by henriquebecker91** [jump-dev/CPLEX.jl#361]
I recently opened an issue in Gurobi (issue [397](https://github.com/jump-dev/Gurobi.jl/issues/397)) because Gurobi has no configurable memory limits but auto-detect memory exhaustion and throws an exception. The solution (PR [398](https://github.com/jump-dev/Gurobi.jl/pull/398)) was to capture the exception and treat it as the solver has stopped the optimization with a `MOI.MEMORY_LIMIT` status.

CPLEX has at least two configurable memory limits. [`CPXPARAM_MIP_Limits_TreeMemory`](https://www.ibm.com/support/knowledgecenter/SSSA5P_20.1.0/ilog.odms.cplex.help/CPLEX/Parameters/topics/TreLim.html) and [`CPXPARAM_WorkMem`](https://www.ibm.com/support/knowledgecenter/SSSA5P_20.1.0/ilog.odms.cplex.help/CPLEX/Parameters/topics/WorkMem.html). The relationship between these limits is not crystal clear: the tree memory limit default is set to an "infinite" value but working memory default is set to 2048MiB, so the tree memory is separate of the working memory. None of these seem to include, for example, the memory needed for solving the root node relaxation in a MIP, because setting the tree limit to lower does not avoid CPLEX throwing [`CPLEX Error  1001: Out of memory.`](https://www.ibm.com/support/knowledgecenter/SSSA5P_20.1.0/ilog.odms.cplex.help/refcallablelibrary/macros/CPXERR_NO_MEMORY.html) and, at least for me, I often solve problems node relaxations larger than the working memory default (2048MiB). In fact, albeit CPLEX has a interface to query the status of a finished optimization (like Gurobi), it does not seem to be a code for each of the two memory limits but only for the tree memory limit: [`CPXMIP_MEM_LIM_FEAS`](https://www.ibm.com/support/knowledgecenter/SSSA5P_20.1.0/ilog.odms.cplex.help/refcallablelibrary/macros/CPXMIP_MEM_LIM_FEAS.html) (for solution available, despite the memory problem) and [`CPXMIP_MEM_LIM_INFEAS`](https://www.ibm.com/support/knowledgecenter/SSSA5P_20.1.0/ilog.odms.cplex.help/refcallablelibrary/macros/CPXMIP_MEM_LIM_INFEAS.html) (for no solution available). There is also [`CPX_STAT_CONFLICT_ABORT_MEM_LIM`](https://www.ibm.com/support/knowledgecenter/SSSA5P_20.1.0/ilog.odms.cplex.help/refcallablelibrary/macros/CPX_STAT_CONFLICT_ABORT_MEM_LIM.html) that seems an odd duck: there is no way to configure its memory limit (is it the working memory?) but it also does not throw an error if it goes out of memory.

My question is: should CPLEX ERROR 1001 be treated as Gurobi ERROR 10001? It seems like even with careful consideration of the practitioner, CPLEX may exhaust memory in subroutine that has no configurable limits, and the handling will need to be different because of that.

**Comment by henriquebecker91** [comment]
Done: #362.

**Comment by odow** [comment]
Closed by #362
