### ISSUE TITLE
How to export a log file during Cplex execution?

### ISSUE THREAD

**Issue by wdscoelho** [jump-dev/CPLEX.jl#363]
Hello,

I'd like to know how to export a log file during Cplex execution with CPLEX.jl v 0.7

With CPLEX.jl v0.6 I set 
  ```
        mockModel=JuMP.backend(my_model).optimizer.model
        CPLEX.set_logfile(mockModel.inner.env,"LOG.log")
        optimize!(my_model)
```

But now I get the following error

> [1] error(::String) at ./error.jl:33
>  [2] getproperty(::CPLEX.Optimizer, ::Symbol) at /home/wesley/.julia/packages/CPLEX/NzKvR/src/CPLEX.jl:71

Could anyone tell me how to do it?

Thanks.
Wesley

**Comment by dourouc05** [comment]
Hi Wesley, 

The package was heavily rewritten by @odow between 0.6 and 0.7, that's why you're having problems (https://github.com/jump-dev/CPLEX.jl/blob/master/README.md). Didn't you get this error message with your code? 

```
ERROR: The C API of CPLEX.jl has been rewritten to expose the complete C API, and
all old functions have been removed. For more information, see the Discourse
announcement: https://discourse.julialang.org/t/ann-upcoming-breaking-changes-to-cplex-jl-and-gurobi-jl/47814

Here is a brief summary of the changes.

* Function names have changed. For example, `CPLEX.close_CPLEX(env)` is now
    `CPXcloseCPLEX(env)`.
* For users of `CPLEX.Optimizer`, `model.inner` has been replaced by the fields
    `model.env` and `model.lp`, which correspond to the environment and problem
    pointers at the C API level. For example:
    ```julia
    stat = CPLEX.get_status(model.inner)
    ```
    is now:
    ```julia
    stat = CPXgetstat(model.env, model.lp)
    ```
* Querying functionality has changed. For example:
    ```julia
    is_point = CPLEX.cbcandidateispoint(cb_data)
    ```
    is now:
    ```julia
    is_point_P = Ref{Cint}()
    CPXcallbackcandidateispoint(cb_data, is_point_P)
    if ret != 0
        # Do something because the call failed
    end
    is_point = is_point_P[]
    ```

The new API is more verbose, but the names and function arguments are now
identical to the C API, documentation for which is available at:
https://www.ibm.com/support/knowledgecenter/SSSA5P_12.10.0/ilog.odms.cplex.help/refcallablelibrary/groups/homepagecallable.html

To revert to the old API, use:

    import Pkg
    Pkg.add(Pkg.PackageSpec(name = "CPLEX", version = v"0.6"))

Then restart Julia for the change to take effect.
```

You may want to use `CPXsetlogfilename` instead. The syntax to access the inner model has also changed a bit, as explained on [Discourse](https://discourse.julialang.org/t/ann-upcoming-breaking-changes-to-cplex-jl-and-gurobi-jl/47814). A complete example: 

```
m = direct_model(CPLEX.Optimizer())
@variable(m, x >= 0)
@constraint(m, x <= 4)
@objective(m, Max, x)
CPXsetlogfilename(backend(m).env, "C:\\Users\\Thibaut\\log.log", "w")
optimize!(m)
open("C:\\Users\\Thibaut\\log.log", "r") do io print(read(io, String)) end
```

```
Version identifier: 20.1.0.0 | 2020-11-10 | 9bedb6d68
Tried aggregator 1 time.
LP Presolve eliminated 1 rows and 1 columns.
All rows and columns eliminated.
Presolve time = 0.01 sec. (0.00 ticks)
```

**Comment by wdscoelho** [comment]
Hello,

Thank you for the answer. It works now.
