### ISSUE TITLE
issue 1217 no solution exist.

### ISSUE THREAD

**Issue by HilaireFoillard** [jump-dev/CPLEX.jl#372]
Hello, I use CPLEX in my program in order to make Bender's cut on big MIP. Since I wanted to strenghten my Benders cut, I use a technique in order to find Pareto optimal cut. This  technics need to solve another problem than the Benders cuts (inspired to Magnanti works). This new problem has exactly the same constraint to the Benders subproblem given before, there is only one new constraint, the combination of variable corresponding to the objective of the Benders subproblem is here put as a constraint which has to be equals to the value of the objective of the Benders subproblem solve just before. There is just a new objective function which aims to find Pareto optimal cuts. So, normaly, since the constraints are exactly the same and the new constraints is the result of the Benders subproblem, the new problem to solve (Pareto optimal cuts) has to have a soluce. But the fact is, sometimes CPLEX give me  the error message, issue 1217 no solutions exist. This is strange because when I use Cbc I find a result for the problem. The fact, is I prefer to solve with CPLEX which is very faster

**Comment by odow** [comment]
From https://www.ibm.com/support/pages/cplex-error-1217-when-editing-and-solving-cplex-models-incrementally

> The most common situation is that users try to access the solutions after the models are modified, such as changing the bounds of variables and/or constraints and changing coefficients of variables in constraints.

The JuMP documentation also warns about this: https://jump.dev/JuMP.jl/stable/manual/solutions/#Recommended-workflow

<img width="828" alt="image" src="https://user-images.githubusercontent.com/8177701/130520955-b059cfb1-d319-4b18-ab4f-42b318b3530c.png">

**Comment by HilaireFoillard** [comment]
Yes but in my code, I create a new model with the same constraint, so I didn't modify the model...

**Comment by HilaireFoillard** [comment]
And I have also sometimes an issue about the fact that no LU factorisation exist

**Comment by odow** [comment]
Please provide a reproducible example

**Comment by odow** [comment]
Closing as stale. I suggest you contact IBM support if the issue persists. It may be a modelling issue, but it doesn't seem like a problem with CPLEX.jl.
