### ISSUE TITLE
Legacy callback functions

### ISSUE THREAD

**Issue by CanLi1** [jump-dev/CPLEX.jl#373]
Hello,

First of all, many thanks for creating this very useful package. It seems that the example in Readme is for using the generic callback of CPLEX. I tried to use some of the legacy callback functions, e.g., 
https://www.ibm.com/docs/en/icos/20.1.0?topic=g-cpxxgetcallbacknodeinfo-cpxgetcallbacknodeinfo

However, I was not successful. I would be very grateful if you could add an example of using the legacy callbacks or pointing me to an existing example. 

Many thanks for your attention to this request.

Best regards,
Can

**Comment by odow** [comment]
Closing because we won't be documenting how to use the legacy callbacks. The generic callback is tested and documented in the README.
