### ISSUE TITLE
[Heuristic Callback] Wrong computation of the `cnt` argument

### ISSUE THREAD

**Issue by Louis-ZIGRAND** [jump-dev/CPLEX.jl#375]
Dear maintainers,

As described in [the IBM documentation](https://www.ibm.com/docs/en/icos/20.1.0?topic=c-cpxxcallbackpostheursoln-cpxcallbackpostheursoln), the `cnt` argument of the `CPXcallbackpostheursoln` method must be the number of elements in `ind` and `val`.

However, as you can see in `src/MOI/MOI_callbacks.jl`, it is currently always set to `Cint(1)`: https://github.com/jump-dev/CPLEX.jl/blob/0deb00b9f1dd63b650bdd9989dd51b8545cd240d/src/MOI/MOI_callbacks.jl#L344-L351

Hence, when the user provides a complete solution through the Heuristic Callback, only the first value of `val` associated to the first variable of `ind` is taken into account by CPLEX.

I think that a fix to this issue would be to replace the `Cint(1)` with `Cint(length(variables))`. At least, it seemed to fix the issue in my current project but I don't know if you would like to add other protections to this process? If you think I'm right and if you wish, I could open a Pull Request on this matter but I don't know if I need any special right to be able to do this?

Also, for your information, the current unitary tests that use the Heuristic Callback do not break on this because it is not an issue if CPLEX does not get a complete solution from this callback as it tries to complete it afterwards.

By the way, thank you a lot for this Julia package, I've used it for a few years already and it's really helpful! :-)

**Comment by odow** [comment]
Good catch. I'm probably to blame for this. I'll open a PR.

**Comment by odow** [comment]
Try updating. It should be fixed now.

**Comment by Louis-ZIGRAND** [comment]
I confirm that it seems to be fixed, from my understanding of the code and the results I get in my project.
Thank you for your time and have a nice day! :-)
