### ISSUE TITLE
Support for CPLEX 12.63

### ISSUE THREAD

**Issue by marianajw** [jump-dev/CPLEX.jl#388]
Is it possible to bring back support for Cplex 12.63?

**Comment by odow** [comment]
Not really. The minimum supported version of CPLEX is 12.10. The latest version is 20.1.

Note that CPLEX.jl is maintained by the JuMP community and is not an official product of IBM. If you require CPLEX.jl support for CPLX 12.6.3, contact IBM for support.

Is it critical? Why can't you update to a more recent version of CPLEX?

**Comment by odow** [comment]
Closing since we won't be supporting CPLEX 12.6.3.
