### ISSUE TITLE
How to import cplex.jl on google colab

### ISSUE THREAD

**Issue by TEKERGUL** [jump-dev/CPLEX.jl#414]
I need to create a optimization problem with the cplex library and julia. I have to use colab for this, I was able to create a colab on the julia template and download the JuMP library. I have a student license on cplex. But when I try to download cplex it gives the following error:

Error building `CPLEX`: 
ERROR: LoadError: Unable to install CPLEX.jl.

The versions of CPLEX supported by CPLEX.jl are:

* 12.10
* 20.1

You must download and install one of these versions separately.

You should set the `CPLEX_STUDIO_BINARIES` environment variable to point to
the install location then try again. For example (updating the path to the
correct location if needed):

On Windows, this might be
ENV["CPLEX_STUDIO_BINARIES"] = "C:\\Program Files\\CPLEX_Studio1210\\cplex\\bin\\x86-64_win\\"
import Pkg
Pkg.add("CPLEX")
Pkg.build("CPLEX")

i tried the import Pkg; Pkg.add("CPLEX") and upload the I uploaded the cplex files on the computer and showed the path there:

ENV["CPLEX_STUDIO_BINARIES"] = "/content/x64_win64"
import Pkg
Pkg.add("CPLEX")
Pkg.build("CPLEX")

**Comment by dourouc05** [comment]
What's in your /content/x64_win64 folder? I think it's supposed to be
directly the binary (i.e. the CPLEX executable file)

**Comment by TEKERGUL** [comment]
"C:\Program Files\IBM\ILOG\CPLEX_Studio2211\cplex\bin\x64_win64\ILOG.Concert.dll"
"C:\Program Files\IBM\ILOG\CPLEX_Studio2211\cplex\bin\x64_win64\ILOG.Concert.xml"
"C:\Program Files\IBM\ILOG\CPLEX_Studio2211\cplex\bin\x64_win64\ILOG.CPLEX.dll"
"C:\Program Files\IBM\ILOG\CPLEX_Studio2211\cplex\bin\x64_win64\ILOG.CPLEX.xml"
"C:\Program Files\IBM\ILOG\CPLEX_Studio2211\cplex\bin\x64_win64\cplex.exe"
"C:\Program Files\IBM\ILOG\CPLEX_Studio2211\cplex\bin\x64_win64\cplex2211.dll"
"C:\Program Files\IBM\ILOG\CPLEX_Studio2211\cplex\bin\x64_win64\cplexamp.exe"
that files in the folder, and i suspucious about the my academic cplex license bcs i claim it and i cant figure out where to find exp. date and anothers in ibm.

**Comment by odow** [comment]
Doesn't Google colab use a linux distribution? You'll need to install the linux version of CPLEX. You can't use a Windows DLL.

**Comment by odow** [comment]
I don't have installation instructions for Google colab, but I'm not aware of any reason why it wouldn't work. You'll need to install the linux distribution of CPLEX. You can't use a dll or `exe` on colab.
