### ISSUE TITLE
How to do "cplex.setout(ofstream)"?

### ISSUE THREAD

**Issue by kaarthiksundar** [jump-dev/CPLEX.jl#42]
When using CPLEX with the concert API, to write the log to an external file; I would do 
     cplex.setOut(outputfilestream)
How to do a similar thing in Julia?

**Comment by joehuchette** [comment]
Try
```
CPLEX.set_logfile(m.env, "myoutputfile.txt")
```
where ``m`` is the ``CPLEX.Model`` object (``model.internalModel.inner`` in JuMP after a call to ``buildInternalModel(model)``).

**Comment by mlubin** [comment]
Hmm, that won't work very well if using an extension like JuMPChance.

**Comment by mlubin** [comment]
(which is the case)

**Comment by mlubin** [comment]
Could we add a parameter for this to the MPB solver object? I.e., ``CplexSolver(logfile="...")``

**Comment by joehuchette** [comment]
How about using the solve hook? 

Using the solver object is alright too if you want to go ahead and do it.

**Comment by mlubin** [comment]
JuMPChance already uses the solve hook. I don't think multiple solve hooks work right now.
@kaarthiksundar, in the meantime, you can try using the trick [here](https://github.com/JuliaOpt/JuMP.jl/blob/master/FAQ.md) to redirect the solver output to a file from Julia.
