### ISSUE TITLE
CPLEX 22.1.1 is not yet supported on Linux

### ISSUE THREAD

**Issue by daichou03** [jump-dev/CPLEX.jl#423]
tl;dr: As an academic user, I can successfully build and use CPLEX.jl on windows with CPLEX 22.1.1, but not on Linux.

Reproducing the issue:
I tried the steps on windows it and all worked out.

I then performed the steps needed to install both CPLEX and CPLEX.jl on Linux.
Firstly, when I do `]build CPLEX`, I got the `"ERROR: LoadError: Unable to install CPLEX.jl."` error.
The environment variables correctly set up.
I tried tampering `_CPX_VERS` in `build.jl` to include `"2211"` and then the `build CPLEX` can go through,
but precompiling it will give
```
[ Info: Precompiling CPLEX [a076750e-1247-5638-91d2-ce28b192dca0]
ERROR: LoadError: You have installed version 22.1.1 of CPLEX, which is not supported
by CPLEX.jl. We require CPLEX version 12.10 or 20.1.

After installing CPLEX, run:

    import Pkg
    Pkg.rm("CPLEX")
    Pkg.add("CPLEX")

Make sure you set the environment variable `CPLEX_STUDIO_BINARIES` following
the instructions in the CPLEX.jl README, which is available at
https://github.com/jump-dev/CPLEX.jl.

If you have a newer version of CPLEX installed, changes may need to be made
to the Julia code. Please open an issue at
https://github.com/jump-dev/CPLEX.jl.
```

**Comment by odow** [comment]
What is `import Pkg; Pkg.status()`?

It looks like you might have installed an old version of CPLEX.jl. 

Try `import Pkg; pkg"add CPLEX@0.9.6"`.

**Comment by odow** [comment]
> I tried tampering _CPX_VERS in build.jl to include "2211" and then the build CPLEX can go through,

For example, this is already included in the latest release:

https://github.com/jump-dev/CPLEX.jl/blob/ea9aec52a2be19727c646561a6d03a3743bd3ffa/deps/build.jl#L13-L18

**Comment by odow** [comment]
Any update on this? If not, I will close. You need the latest version of CPLEx.jl to use CPLEX 22.1.1

**Comment by daichou03** [comment]
It turned out to be the version of Julia installed on the Linux was too low, so the version of CPLEX.jl, when installed via `]add CPLEX`, was outdated. `import Pkg; pkg"add CPLEX@0.9.6"` did help reveal this issue - thanks for your input and this case can be closed.

**Comment by odow** [comment]
Glad to hear you got it sorted
