### ISSUE TITLE
CPLEX does not work with version 22.1.1

### ISSUE THREAD

**Issue by RaimundK2** [jump-dev/CPLEX.jl#426]
After installing and calling using CPLEX, I get

ERROR: LoadError: You have installed version 22.1.1 of CPLEX, which is not supported
by CPLEX.jl. We require CPLEX version 12.10 or 20.1.

After installing CPLEX, run:

    import Pkg
    Pkg.rm("CPLEX")
    Pkg.add("CPLEX")
etc ...

Interestingly CPLEX.jl worked without problems with the same CPLEX version until two days ago.

**Comment by odow** [comment]
You need CPLEX.jl v0.9.6 or v0.9.7 to use CPLEX 22.1.1.

Check `import Pkg; Pkg.status()`.

**Comment by RaimundK2** [comment]
Thanks for the quick answer. Strangely enough, it seems that the correct version has been replaced by an older one - maybe through some installation of another package (?) updated to the new one
________________________________
Von: Oscar Dowson ***@***.***>
Gesendet: Dienstag, 21. März 2023 00:22
An: jump-dev/CPLEX.jl ***@***.***>
Cc: Raimund Kovacevic ***@***.***>; Author ***@***.***>
Betreff: Re: [jump-dev/CPLEX.jl] CPLEX does not work with version 22.1.1 (Issue #426)


You need CPLEX.jl v0.9.6 or v0.9.7 to use CPLEX 22.1.1.

Check import Pkg; Pkg.status().

**Comment by odow** [comment]
Yes, another package is likely holding you back. You can see which if you run `import Pkg; Pkg.pkg"add CPLEX@0.9.7"`..

**Comment by odow** [comment]
Any update on this?

**Comment by odow** [comment]
Closing as stale. The latest version of CPLEX.jl does with 22.1.1, so anyone experiencing this in future should update their packages.

**Comment by harshangrjn** [comment]
@odow I still get this issue on Mac M2 with `CPLEX 22.1` and `CPLEX.jl v1.0.2`. I have the `ENV["CPLEX_STUDIO_BINARIES"]` set up correctly. But `build CPLEX` keeps giving this error and doesn't build:  
```
ERROR: Error building `CPLEX`: 
You should set the `CPLEX_STUDIO_BINARIES` environment variable 
```
Is there something I am missing?

**Comment by odow** [comment]
What is `ENV["CPLEX_STUDIO_BINARIES"]`? Did you install the `aarch64` build of CPLEX?

**Comment by harshangrjn** [comment]
`ENV["CPLEX_STUDIO_BINARIES"] = "/Applications/CPLEX_Studio221/cplex/bin/x86-64_osx/"` 

Not sure of `aarch64` build. Installed the version from the IBM website for Mac OS and didn't throw any error during installation.

**Comment by odow** [comment]
This looks like you installed the intel version: `x86-64`

**Comment by harshangrjn** [comment]
I see! Let me try the ARM version.

**Comment by odow** [comment]
It wouldn't error on install because Apple has a compatibility layer called Rosetta. But you need to make sure that the build of CPLEX is the same as the build of Julia. So both x86 or both aarch64. If you have a mis-match they can't find each other.

**Comment by harshangrjn** [comment]
Which version of CPLEX.jl is compatible with x86? ARM build installation is crashing for some reason on M2.

**Comment by harshangrjn** [comment]
Great - that works! I had installed the `Apple Silicon` version of Julia, but the CPLEX-ARM installation crashes without giving any specific error. But Julia-rosetta + CPLEX-22.1-rosetta with recent CPLEX.jl all work fine.
