### ISSUE TITLE
Screenoutput in CPLEX version 22.1.1

### ISSUE THREAD

**Issue by arnedecadt** [jump-dev/CPLEX.jl#435]
I'm trying to suppress output while I pass a solver to another package (Polyhedra.jl) as a parameter. I tried to do this as in https://stackoverflow.com/questions/55824381/how-to-mute-jump-using-cplex-log-progress by setting `CPXPARAM_ScreenOutput=0` but this threw a MethodError:
```
ERROR: MethodError: no method matching CPLEX.Optimizer(; CPXPARAM_ScreenOutput::Int64)

Closest candidates are:
  CPLEX.Optimizer() got unsupported keyword argument "CPXPARAM_ScreenOutput"
   @ CPLEX ~/.julia/packages/CPLEX/Vd1Gd/src/MOI/MOI_wrapper.jl:265
  CPLEX.Optimizer(::Union{Nothing, CPLEX.Env}) got unsupported keyword argument "CPXPARAM_ScreenOutput"
   @ CPLEX ~/.julia/packages/CPLEX/Vd1Gd/src/MOI/MOI_wrapper.jl:265
 ```
I would like to request support for this functionality.

**Comment by odow** [comment]
Use 
```julia
using JuMP, CPLEX
model = Model(CPLEX.Optimizer)
set_silent(model)
# or
model = Model(CPLEX.Optimizer)
set_attribute(model, "CPXPARAM_ScreenOutput", 0)
```

**Comment by arnedecadt** [comment]
Thank you for your quick response, but the problem is that I pass the _solver_ (not a model) to another package (Polyhedra.jl) as a parameter. (I already had the proposed solution in other parts of my code.) I use for example `removevredundancy(V, CPLEX.Optimizer)` ( https://juliapolyhedra.github.io/Polyhedra.jl/stable/redundancy/#Polyhedra.removevredundancy ). Is it possible to set the solver silent for every possible model? 

I tried MOI.Silent() which didn't work and changing the internal parameter which wasn't allowed.

**Comment by odow** [comment]
Then pass `MOI.OptimizerWithAttributes(CPLEX.Optimizer, MOI.Silent() => true)`

**Comment by odow** [comment]
No problem
