### ISSUE TITLE
Installation problems with Apple M1 and CPLEX 22.1.1

### ISSUE THREAD

**Issue by ZacharieALES** [jump-dev/CPLEX.jl#439]
I have two students with an Apple M1 who are not able to build the package. They are using CPLEX 22.1.1 which is supposed to be compatible with M1.

Here is the results of commands versioninfo() and Pkg.status("CPLEX") for both of them:
```
> versioninfo()
Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores

> Pkg.status("CPLEX")
Status `~/.julia/environments/v1.9/Project.toml`
  [a076750e] CPLEX v1.0.1
```

The folder indicated in variable ENV["CPLEX_STUDIO_BINARIES"] contains the following files:
- cplex
- cplexamp
- libcplex2211.dylib

They installed CPLEX version 12.10 first but I checked that ENV["CPLEX_STUDIO_BINARIES"] points toward the folder of version 22.1.1.

Any idea what could be wrong?

**Comment by odow** [comment]
Did they download and install the M1 version of CPLEX? What is the full output of `import Pkg; Pkg.build("CPLEX")`?

**Comment by ZacharieALES** [comment]
It worked with the arm version. Sorry about that, they told me they already tried before I made the issue...

**Comment by ZacharieALES** [comment]
Closing
