### ISSUE TITLE
Memory cleaning

### ISSUE THREAD

**Issue by matheusdiogenesandrade** [jump-dev/CPLEX.jl#443]
Hello.

I am trying to promote further analysis on the memory management, and, at the moment, I am looking for the snippets responsible for calling the `end()` function (cf. [here](https://www-eio.upc.es/lceio/manuals/cplex-11/html/refcppcplex/html/classes/IloExtractable.html#method_end) and [here](https://www-eio.upc.es/lceio/manuals/cplex-11/html/refcppcplex/html/classes/IloEnv.html#method_end) for the C++ API reference) of the Cplex C API in the julia code. I would like to know if someone could point me such snippets.

Thanks and regards.

**Comment by odow** [comment]
CPLEX.jl  does not use the C+++ API, so it does not call `end()`.

Objects are freed via a finalizer that runs when Julia's GC frees the associated CPLEX `Model` or `Env`

https://github.com/jump-dev/CPLEX.jl/blob/6e0fdafc7df51bb710fb3e95f5bb7563ec984f65/src/MOI/MOI_wrapper.jl#L88-L95

https://github.com/jump-dev/CPLEX.jl/blob/6e0fdafc7df51bb710fb3e95f5bb7563ec984f65/src/MOI/MOI_wrapper.jl#L284-L297

I assume this questions is related to https://discourse.julialang.org/t/memory-management-in-cplex-jl/109704. I don't have any suggestions other than what I mentioned there.

**Comment by matheusdiogenesandrade** [comment]
Thank you very much, that is exactly what I am looking for.
