### ISSUE TITLE
How does CPX_CALLBACK_INFO_NODE_COUNT work?

### ISSUE THREAD

**Issue by matheusdiogenesandrade** [jump-dev/CPLEX.jl#446]
I am trying to understand how the triad CPLEX.jl + JuMP.jl + MOI.jl make the function [`node_count`](https://github.com/jump-dev/JuMP.jl/blob/3272815d449f9243bb2bd91ab683bc5b3c651ffd/src/optimizer_interface.jl#L686) work. So, in the CPLEX.jl we have at line [329](https://github.com/jump-dev/CPLEX.jl/blob/c986eed415235785e551c51ebff9061aa8975e95/src/gen2210/libcpx_common.jl#L329):

```julia
const CPX_CALLBACK_INFO_NODE_COUNT = 103
```

In the JuMP.jl we have [this](https://github.com/jump-dev/JuMP.jl/blob/3272815d449f9243bb2bd91ab683bc5b3c651ffd/src/optimizer_interface.jl#L686):

```julia
function node_count(model::GenericModel)
    return MOI.get(model, MOI.NodeCount())
end
```

And, in the MOI.jl we have [this](https://github.com/jump-dev/MathOptInterface.jl/blob/0f250c0499dbad8c99a21660bca1be44a4eed0e3/src/attributes.jl#L1374):

```julia
"""
    NodeCount()

A model attribute for the total number of branch-and-bound nodes explored while
solving a mixed-integer program (MIP).
"""
struct NodeCount <: AbstractModelAttribute end
```

Precisely, where exactly the delegation to some cplex CPX function is made to retrieve this info?

Thanks and regards.

**Comment by odow** [comment]
NodeCount is implemented here: 

https://github.com/jump-dev/CPLEX.jl/blob/c986eed415235785e551c51ebff9061aa8975e95/src/MOI/MOI_wrapper.jl#L3308-L3311

`CPX_CALLBACK_INFO_NODE_COUNT` is unrelated. It is an attribute that can be queried in a callback. See:
https://github.com/jump-dev/CPLEX.jl/tree/master?tab=readme-ov-file#callbacks

**Comment by matheusdiogenesandrade** [comment]
Thank you so much.
